### PR TITLE
Fix resolve of astroViteConfigs.js on Windows

### LINKED ISSUE #63: Missing astroViteConfigs.js reported with latest v0.6.4
Hi,

thank you for this plugin it is really needed!

I have encountered `error ENOENT: no such file or directory, open '...../astroViteConfigs.js'` when running the latest v0.6.4 with astro `1.0.0-beta.27`. I have used a plain installation with `react` and `tailwind`integrations. and my config looks like this:
```
import { defineConfig } from 'astro/config';
import react from "@astrojs/react";
import tailwind from "@astrojs/tailwind";
import sitemap from "@astrojs/sitemap";

import { astroImageTools } from "astro-imagetools";

// https://astro.build/config
export default defineConfig({
  integrations: [react(), tailwind(), sitemap(), astroImageTools],
  experimental: {
    integrations: true
  }
});
```

when rolling back to v0.6.3 this error is not reported.

### PR DESCRIPTION
**Pull request by IanVS**
This fixes #63 as suggested by @AirBorne04 in https://github.com/RafidMuhymin/astro-imagetools/issues/63#issuecomment-1129669677.

Once we have a few end-to-end tests set up, the CI matrix should catch these kinds of issues.

### CODE REVIEW

File: packages/astro-imagetools/integration/index.js [hunk 1]
```diff
@@ -1,15 +1,12 @@
 // @ts-check
 import fs from "node:fs";
-import path from "node:path";
+import { posix as path, resolve } from "path";
```
Comment (RafidMuhymin) [inline packages/astro-imagetools/integration/index.js:3]: As the other imports are prefixed with `node:`, can you prefix it too to avoid any kind of compatibility issues?
